name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./             # جذر مشروعك
          server-dir: /htdocs/      # مجلد المشروع على الاستضافة
          exclude: |
            .env
            public/.htaccess
          dangerous-clean-slate: false  # مهم جداً لمنع حذف الملفات الموجودة مسبقًا


